### ISSUE TITLE
RTSP Server

### ISSUE THREAD

**Issue by dariofil-star** [jimm98y/SharpRealTimeStreaming#1]
Hi, any example of how to use vlc/ffmpeg/gstreamer to feed the RTSP server an RTP stream?

**Comment by dariofil-star** [comment]
for Example;
I want to use ffmpeg (or similar) to trancode the video file and send out an RTP stream.
RTSP server is required by the consuming application and cant feed rtp directly.

**Comment by jimm98y** [comment]
That's a great idea, however in the current state it'll need a few code changes. I'll see what I can do.
